//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.11.2
//     from Assets/Conroles.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @Conroles: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @Conroles()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""Conroles"",
    ""maps"": [
        {
            ""name"": ""PlayerNeutral"",
            ""id"": ""694c1863-9797-48b0-9024-a35fcaa1a2c0"",
            ""actions"": [
                {
                    ""name"": ""Movement"",
                    ""type"": ""Value"",
                    ""id"": ""abc658a2-ba7a-4f31-84dd-b0a6f714b56d"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Look"",
                    ""type"": ""Value"",
                    ""id"": ""15053025-8cc3-4ff4-ae21-50a0137feb1e"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""daa5424a-98c6-45dc-a17b-98f769eb8b99"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""1c886211-4e78-480c-b400-b0e2dfcfed6e"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""c7924f78-9278-46b2-aa11-88ee896dfa32"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""112405d2-0861-4627-ad43-44b39afd147f"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""4d20bf0a-849f-47fa-a68b-93b837bf5e44"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""b776ae2e-736a-4829-852f-064873df49d6"",
                    ""path"": ""<Mouse>/delta"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Look"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // PlayerNeutral
        m_PlayerNeutral = asset.FindActionMap("PlayerNeutral", throwIfNotFound: true);
        m_PlayerNeutral_Movement = m_PlayerNeutral.FindAction("Movement", throwIfNotFound: true);
        m_PlayerNeutral_Look = m_PlayerNeutral.FindAction("Look", throwIfNotFound: true);
    }

    ~@Conroles()
    {
        UnityEngine.Debug.Assert(!m_PlayerNeutral.enabled, "This will cause a leak and performance issues, Conroles.PlayerNeutral.Disable() has not been called.");
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // PlayerNeutral
    private readonly InputActionMap m_PlayerNeutral;
    private List<IPlayerNeutralActions> m_PlayerNeutralActionsCallbackInterfaces = new List<IPlayerNeutralActions>();
    private readonly InputAction m_PlayerNeutral_Movement;
    private readonly InputAction m_PlayerNeutral_Look;
    public struct PlayerNeutralActions
    {
        private @Conroles m_Wrapper;
        public PlayerNeutralActions(@Conroles wrapper) { m_Wrapper = wrapper; }
        public InputAction @Movement => m_Wrapper.m_PlayerNeutral_Movement;
        public InputAction @Look => m_Wrapper.m_PlayerNeutral_Look;
        public InputActionMap Get() { return m_Wrapper.m_PlayerNeutral; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PlayerNeutralActions set) { return set.Get(); }
        public void AddCallbacks(IPlayerNeutralActions instance)
        {
            if (instance == null || m_Wrapper.m_PlayerNeutralActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_PlayerNeutralActionsCallbackInterfaces.Add(instance);
            @Movement.started += instance.OnMovement;
            @Movement.performed += instance.OnMovement;
            @Movement.canceled += instance.OnMovement;
            @Look.started += instance.OnLook;
            @Look.performed += instance.OnLook;
            @Look.canceled += instance.OnLook;
        }

        private void UnregisterCallbacks(IPlayerNeutralActions instance)
        {
            @Movement.started -= instance.OnMovement;
            @Movement.performed -= instance.OnMovement;
            @Movement.canceled -= instance.OnMovement;
            @Look.started -= instance.OnLook;
            @Look.performed -= instance.OnLook;
            @Look.canceled -= instance.OnLook;
        }

        public void RemoveCallbacks(IPlayerNeutralActions instance)
        {
            if (m_Wrapper.m_PlayerNeutralActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IPlayerNeutralActions instance)
        {
            foreach (var item in m_Wrapper.m_PlayerNeutralActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_PlayerNeutralActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public PlayerNeutralActions @PlayerNeutral => new PlayerNeutralActions(this);
    public interface IPlayerNeutralActions
    {
        void OnMovement(InputAction.CallbackContext context);
        void OnLook(InputAction.CallbackContext context);
    }
}
